---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carts
  labels:
    app: carts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carts
  template:
    metadata:
      labels:
        app: carts
    spec:
      containers:
        - name: carts
          image: carts
          ports:
            - containerPort: 5040
          resources:
            requests:
              memory: "120Mi"
              cpu: "80m"
            limits:
              memory: "600Mi"
              cpu: "320m"

---
apiVersion: v1
kind: Service
metadata:
  name: carts-service
spec:
  selector:
    app: carts
  ports:
    - port: 5040
      protocol: TCP
      name: tcp-5040
      targetPort: 5040
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: carts-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: carts
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
