apiVersion: apps/v1
kind: Deployment
metadata:
  name: kraken
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kraken
  template:
    metadata:
      labels:
        app: kraken
    spec:
      containers:
        - name: kraken
          image: kraken
          ports:
            - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
          env:
            - name: KRAKEND_PORT
              value: "8080"
          resources:
            requests:
              memory: "350Mi"
              cpu: "60m"
            limits:
              memory: "1000Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: kraken
spec:
  selector:
    app: kraken
  ports:
    - port: 8080
      targetPort: 8080
      name: gateway
    - port: 8081
      targetPort: 8081
      name: metrics
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kraken-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kraken
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
