---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  labels:
    app: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: orders
          ports:
            - containerPort: 5010
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: orders-service
spec:
  selector:
    app: orders
  ports:
    - port: 5010
      protocol: TCP
      name: tcp-5010
      targetPort: 5010
# ---
# apiVersion: gateway.networking.k8s.io/v1
# kind: HTTPRoute
# metadata:
#   name: orders
#   annotations:
#     konghq.com/strip-path: 'true'
# spec:
#   parentRefs:
#     - name: kong
#   rules:
#     - matches:
#         - path:
#             type: PathPrefix
#             value: /orders
#       backendRefs:
#         - name: orders-service
#           kind: Service
#           port: 5010
