---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipments
  labels:
    app: shipments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipments
  template:
    metadata:
      labels:
        app: shipments
    spec:
      containers:
        - name: shipments
          image: shipments
          ports:
            - containerPort: 5060
---
apiVersion: v1
kind: Service
metadata:
  name: shipments-service
spec:
  selector:
    app: shipments
  ports:
    - port: 5060
      protocol: TCP
      name: tcp-5060
      targetPort: 5060
