prometheus:
  prometheusSpec:
    scrapeInterval: 30s
    evaluationInterval: 30s
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    additionalScrapeConfigs:
      - job_name: 'products'
        scrape_interval: 30s
        scrape_timeout: 10s
        kubernetes_sd_configs:
          - role: service
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: products-service
      - job_name: 'users'
        scrape_interval: 30s
        scrape_timeout: 10s
        kubernetes_sd_configs:
          - role: service
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: users-service
      - job_name: 'orders'
        scrape_interval: 30s
        scrape_timeout: 10s
        kubernetes_sd_configs:
          - role: service
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: orders-service
      - job_name: 'payments'
        scrape_interval: 30s
        scrape_timeout: 10s
        kubernetes_sd_configs:
          - role: service
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: payments-service
      - job_name: 'carts'
        scrape_interval: 30s
        scrape_timeout: 10s
        kubernetes_sd_configs:
          - role: service
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: carts-service
      - job_name: 'keycloak'
        scrape_interval: 30s
        scrape_timeout: 10s
        kubernetes_sd_configs:
          - role: service
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: keycloak
      - job_name: 'kraken'
        scrape_interval: 30s
        scrape_timeout: 10s
        kubernetes_sd_configs:
          - role: service
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: kraken
          - source_labels: [__meta_kubernetes_service_port_name]
            action: keep
            regex: metrics
  grafana:
    persistence:
      enabled: true
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: 'default'
            orgId: 1
            folder: ''
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
    dashboards:
      default:
        kic-dash:
          gnetId: 15662
          datasource: Prometheus
        krakend:
          gnetId: 20651
          datasource: Prometheus
