{
 "title": "FastAPI Observabilitys Copy",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "label": "Service", "query": { "query": "label_values(job)" } },
   { "name": "log_keyword", "label": "Log Query" },
   { "name": "query0", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Requests Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{handler!=\"/metrics\", job=\"$job\"}",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total{job=\"$job\", path!=\"/metrics\"})"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum{job=\"$job\"} / http_request_duration_seconds_count{job=\"$job\"}",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Number of 4xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"$job\", status=\"4xx\", handler!~\"none\"}[1m])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Percent of 4xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(http_requests_total{job=\"$job\", status=~\"4xx\", path!=\"/metrics\"}) / sum by(path) (http_requests_total{job=\"$job\", path!=\"/metrics\"})",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Number of 5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"products\", status=~\"5xx\", handler!~\"none\"}[1m])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Percent of 5xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(http_requests_total{job=\"$job\", status=~\"5xx\", path!=\"/metrics\"}) / sum by(path) (http_requests_total{job=\"$job\", path!=\"/metrics\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total{job=\"$job\", status=~\"2xx\", path!=\"/metrics\"}) / sum by(path) (http_requests_total{job=\"$job\", path!=\"/metrics\"})",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Request Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"$job\"}[1m])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "P50 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(handler, le) (rate(http_request_duration_seconds_bucket{job=\"$job\", handler!=\"/metrics\"}[1m])))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "P90 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by(handler, le) (rate(http_request_duration_seconds_bucket{job=\"$job\", handler!=\"/metrics\"}[1m])))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "P95 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(handler, le) (rate(http_request_duration_seconds_bucket{job=\"$job\", handler!=\"/metrics\"}[1m])))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Log of All FastAPI App",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "{app=\"$job\"} | __error__=``"
    }
   ]
  }
 ]
}