---
version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: products-db-service
    ports:
      - "27017:27017"

  product-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product-service
    ports:
      - "5000:5000"
    environment:
      ENV: dev
    depends_on:
      - mongodb

volumes:
  mongodb_data:
