apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-db
  template:
    metadata:
      labels:
        app: products-db
    spec:
      containers:
      - name: products-db
        image: postgres:16.2-alpine3.19
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: products-db-secret
                key: postgres-user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: products-db-secret
                key: postgres-password
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: products-db-secret
                key: postgres-db
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: init-script 
        configMap:
          name: init-sql-configmap-products
---
apiVersion: v1
kind: Service
metadata:
  name: products-db
spec:
  selector:
    app: products-db
  ports:
    - protocol: TCP
      port: 5432
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-sql-configmap-products
data:
  init.sql: |
    -- Drop tables if they already exist
    DROP TABLE IF EXISTS products CASCADE;

      -- Create products table
      CREATE TABLE products (
          id SERIAL PRIMARY KEY,
          name VARCHAR(255) NOT NULL,
          description TEXT,
          price FLOAT NOT NULL,
          image BYTEA,
          stock INT,
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          discount FLOAT DEFAULT 0 CHECK (discount >= 0 AND discount <= 1),
          category VARCHAR(255) DEFAULT 'uncategorized'
      );