---
name: Run Unit Tests (Carts)

on:   # yamllint disable-line rule:truthy
  push:
    paths:
      - 'services/carts/**'

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r services/carts/tests/requirements.txt
          pip install mypy
          pip install pre-commit

      - name: Run pre-commit checks
        run: |
          cd services/carts
          pre-commit run --all-files

      - name: Run unit tests
        run: |
          cd services/carts
          ./scripts/test.sh
