name: Run Unit Tests and Push to DockerHub (carts)

on:
  push:
    paths:
      - "services/carts/**"

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r services/carts/tests/requirements.txt
          pip install pre-commit

      - name: Run unit tests
        run: |
          cd services/carts
          ./scripts/test.sh

      # Build and Push Docker Image steps
      - name: Build Docker image
        if: success() # Only runs if unit tests pass
        run: |
          cd services/carts
          docker build -t flexer89/carts-service:latest .

      - name: Log in to DockerHub
        if: success()
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image
        if: success()
        run: |
          docker tag flexer89/carts-service:latest flexer89/carts-service:latest
          docker push flexer89/carts-service:latest
