name: YAML Lint

on:
  push:
    paths:
      - 'deployments/**'

jobs:
  yamllint:
    name: YAML Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install yamllint
        run: |
          pip install yamllint

      - name: Run yamllint
        run: |
          yamllint .
