name: Run Unit Tests

on:
  push:
    paths:
      - 'services/**'
jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11' 
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r service/${{ matrix.service }}/tests/requirements.txt
          pip install mypy
          pip install pre-commit

      - name: Run pre-commit checks
        run: |
          cd service/${{ matrix.service }}
          pre-commit run --all-files

      - name: Run unit tests for the updated service
        run: |
          cd service/${{ matrix.service }}
          ./tests/test.sh

      - name: Check typing
        run: |
          cd service/${{ matrix.service }}
          mypy --strict .
      
    strategy:
      matrix:
        service: [products, carts, orders, payments, users]
